// Writes Bleepforge JSON edits back to .tres files in the Godot project.
//
// Per-domain entry points (writeItemTres, writeKarmaTres, writeQuestTres,
// writeDialogTres) each:
//   1. Locate the matching .tres under GODOT_PROJECT_ROOT.
//   2. Parse via the round-trip parser.
//   3. Pre-resolve any asset UIDs the mapper might need (item .tres,
//      texture .import sidecars, script paths).
//   4. Call the domain mapper with a fully-populated context.
//   5. Emit and write atomically (temp file + rename).
//
// Returns `{ attempted, ok, path, warnings, error }`. JSON callers should
// treat .tres write as best-effort: a failure here does not invalidate the
// JSON save (which is authoritative for Bleepforge).

import { readFile, rename, writeFile } from "node:fs/promises";
import { dirname, join, resolve, sep } from "node:path";

import { config } from "../../config.js";
import type {
  Balloon,
  DialogSequence,
  FactionData,
  Item,
  KarmaImpact,
  Npc,
  Quest,
} from "@bleepforge/shared";
import { projectIndex } from "../../lib/projectIndex/index.js";
import { parseTres } from "./parser.js";
import { emitTres } from "./emitter.js";
import { removeOrphanExtResources } from "./mutate.js";
import { applyItemScalars, type ItemJson } from "./domains/item.js";
import { applyKarma, type KarmaJson } from "./domains/karma.js";
import { applyDialog, type DialogApplyContext, type DialogSequenceJson } from "./domains/dialog.js";
import { applyFactionScalars, type FactionJson } from "./domains/faction.js";
import {
  applyNpcCasualRemarks,
  applyNpcLootTable,
  applyNpcQuests,
  applyNpcScalars,
  type CasualRemarksApplyContext,
  type LootTableJson,
  type NpcJson,
  type NpcLootApplyContext,
  type NpcQuestApplyContext,
  type NpcQuestEntryJson,
} from "./domains/npc.js";
import { applyBalloonScalars, type BalloonJson } from "./domains/balloon.js";
import { applyQuest, type QuestApplyContext, type QuestJson } from "./domains/quest.js";
import {
  findScriptUidInProject,
  readBalloonUid,
  readItemUid,
  readSceneUid,
  readTextureUid,
} from "./uidLookup.js";

export interface TresWriteResult {
  attempted: boolean;
  ok?: boolean;
  path?: string;
  warnings?: string[];
  error?: string;
}

const NOT_ATTEMPTED: TresWriteResult = { attempted: false };

// Tracks paths Bleepforge wrote recently so the file watcher can ignore
// the change events generated by its own saves (otherwise: write → watcher
// fires → re-import → emit sync event → … wasted work). Keyed by absolute
// path, value is the timestamp of the latest self-write.
const SELF_WRITE_TTL_MS = 1500;
const recentSelfWrites = new Map<string, number>();

export function noteSelfWrite(absPath: string): void {
  recentSelfWrites.set(absPath, Date.now());
  // Opportunistic GC.
  if (recentSelfWrites.size > 200) {
    const cutoff = Date.now() - SELF_WRITE_TTL_MS;
    for (const [p, ts] of recentSelfWrites) {
      if (ts < cutoff) recentSelfWrites.delete(p);
    }
  }
}

// Returns true if `absPath` was written by us within the TTL window.
export function isRecentSelfWrite(absPath: string): boolean {
  const ts = recentSelfWrites.get(absPath);
  if (!ts) return false;
  if (Date.now() - ts > SELF_WRITE_TTL_MS) {
    recentSelfWrites.delete(absPath);
    return false;
  }
  return true;
}

// Returns true when the Godot project root is configured. .tres write-back
// is the canonical save path now (JSON is a derived cache), so the only
// reason to short-circuit is "no Godot project to write to" — which the
// boot-time check makes a hard error anyway. Kept as a guard so the writer
// modules stay defensible if config evolves.
export function shouldWriteTres(): boolean {
  return !!config.godotProjectRoot;
}

export const tresNotAttempted = (): TresWriteResult => NOT_ATTEMPTED;

// ---- Per-domain writers ---------------------------------------------------

export async function writeItemTres(json: Item): Promise<TresWriteResult> {
  if (!shouldWriteTres()) return NOT_ATTEMPTED;
  const root = config.godotProjectRoot!;
  const found = await findItemTres(root, json.Slug);
  if (!found) return { attempted: true, ok: false, error: `no .tres for slug "${json.Slug}"` };

  // Pre-resolve the Icon texture UID (if Icon is set) so the apply pass
  // stays synchronous. readTextureUid reads the .png.import sidecar.
  const iconUid = json.Icon ? await readTextureUid(json.Icon) : null;
  const textureCtx = {
    godotRoot: root,
    resolveTextureUid: (abs: string) => (abs === json.Icon ? iconUid : null),
  };

  return runWrite(found.path, (doc) => {
    const resourceSection = doc.sections.find((s) => s.kind === "resource");
    if (!resourceSection) return ["no [resource] section"];
    const result = applyItemScalars(doc, resourceSection, json as ItemJson, textureCtx);
    return result.warnings;
  });
}

export async function writeFactionTres(json: FactionData): Promise<TresWriteResult> {
  if (!shouldWriteTres()) return NOT_ATTEMPTED;
  const root = config.godotProjectRoot!;
  const found = await findFactionTres(root, json.Faction);
  if (!found) return { attempted: true, ok: false, error: `no .tres for faction "${json.Faction}"` };

  // Pre-resolve Icon + Banner texture UIDs.
  const uidCache = new Map<string, string | null>();
  for (const abs of [json.Icon, json.Banner]) {
    if (abs && !uidCache.has(abs)) uidCache.set(abs, await readTextureUid(abs));
  }
  const textureCtx = {
    godotRoot: root,
    resolveTextureUid: (abs: string) => uidCache.get(abs) ?? null,
  };

  return runWrite(found.path, (doc) => {
    const resourceSection = doc.sections.find((s) => s.kind === "resource");
    if (!resourceSection) return ["no [resource] section"];
    const result = applyFactionScalars(
      doc,
      resourceSection,
      json as FactionJson,
      textureCtx,
    );
    return result.warnings;
  });
}

export async function writeNpcTres(json: Npc): Promise<TresWriteResult> {
  if (!shouldWriteTres()) return NOT_ATTEMPTED;
  const root = config.godotProjectRoot!;
  const found = await findNpcTres(root, json.NpcId);
  if (!found) {
    return { attempted: true, ok: false, error: `no .tres for npc "${json.NpcId}"` };
  }

  // Pre-resolve UIDs the LootTable mapper might need: the two loot scripts
  // (so we can add ext_resources for them when the .tres doesn't already
  // reference them — Korjack-style "no LootTable yet" case), and a UID per
  // unique PickupScene path used by the JSON entries (so each LootEntry can
  // be wired to the correct PackedScene ext_resource).
  const lootTableScriptUid = json.LootTable
    ? await findScriptUidInProject(root, "res://shared/components/loot/LootTable.cs")
    : null;
  const lootEntryScriptUid =
    json.LootTable && json.LootTable.Entries.length > 0
      ? await findScriptUidInProject(root, "res://shared/components/loot/LootEntry.cs")
      : null;
  const sceneUidCache = new Map<string, string | null>();
  if (json.LootTable) {
    for (const entry of json.LootTable.Entries) {
      if (!entry.PickupScene) continue;
      if (sceneUidCache.has(entry.PickupScene)) continue;
      sceneUidCache.set(entry.PickupScene, await readSceneUid(root, entry.PickupScene));
    }
  }
  const lootCtx: NpcLootApplyContext = {
    lootTableScriptUid,
    lootEntryScriptUid,
    resolveSceneUid: (path) => sceneUidCache.get(path) ?? null,
  };

  // Pre-resolve refs for the Quests[] writer:
  //   - NpcQuestEntry.cs script UID (only needed when entries > 0).
  //   - For every unique DialogSequence Id mentioned across all 5 ref slots
  //     of all entries, the matching .tres path + UID. We use boot-time
  //     discovery to enumerate DialogSequence files (no hardcoded folders),
  //     then do a content match for `Id = "<seq>"` to find the right one.
  const npcQuestEntryScriptUid =
    json.Quests.length > 0
      ? await findScriptUidInProject(
          root,
          "res://shared/components/quest/NpcQuestEntry.cs",
        )
      : null;
  const dialogIds = new Set<string>();
  for (const e of json.Quests) {
    for (const id of [
      e.OfferDialog,
      e.AcceptedDialog,
      e.InProgressDialog,
      e.TurnInDialog,
      e.PostQuestDialog,
    ]) {
      if (id) dialogIds.add(id);
    }
  }
  const dialogRefCache = new Map<
    string,
    { resPath: string; uid: string } | null
  >();
  for (const id of dialogIds) {
    const entry = projectIndex.get("dialog", id);
    if (entry && entry.uid) {
      dialogRefCache.set(id, { resPath: entry.resPath, uid: entry.uid });
    } else {
      dialogRefCache.set(id, null);
    }
  }
  const questCtx: NpcQuestApplyContext = {
    npcQuestEntryScriptUid,
    resolveDialogRef: (id) => dialogRefCache.get(id) ?? null,
  };

  // Pre-resolve balloon refs for CasualRemarks. Each balloon-id is
  // `<folder>/<basename>`; we read its .tres header for the UID, then
  // construct the res:// path. Cached by id so duplicate entries (rare —
  // arrays are usually distinct) only do one read.
  const balloonRefCache = new Map<
    string,
    { resPath: string; uid: string } | null
  >();
  for (const id of new Set(json.CasualRemarks)) {
    if (!id) continue;
    const slash = id.indexOf("/");
    if (slash < 0) {
      balloonRefCache.set(id, null);
      continue;
    }
    const folder = id.slice(0, slash);
    const basename = id.slice(slash + 1);
    const uid = await readBalloonUid(root, folder, basename);
    if (!uid) {
      balloonRefCache.set(id, null);
      continue;
    }
    balloonRefCache.set(id, {
      resPath: `res://characters/npcs/${folder}/balloons/${basename}.tres`,
      uid,
    });
  }
  const remarksCtx: CasualRemarksApplyContext = {
    resolveBalloonRef: (id) => balloonRefCache.get(id) ?? null,
  };

  return runWrite(found.path, (doc) => {
    const resourceSection = doc.sections.find((s) => s.kind === "resource");
    if (!resourceSection) return ["no [resource] section"];
    const scalars = applyNpcScalars(resourceSection, json as NpcJson);
    const loot = applyNpcLootTable(
      doc,
      resourceSection,
      json.LootTable as LootTableJson | null,
      lootCtx,
    );
    const quests = applyNpcQuests(
      doc,
      resourceSection,
      json.Quests as NpcQuestEntryJson[],
      questCtx,
    );
    const remarks = applyNpcCasualRemarks(
      doc,
      resourceSection,
      json.CasualRemarks,
      remarksCtx,
    );
    return [
      ...scalars.warnings,
      ...loot.warnings,
      ...quests.warnings,
      ...remarks.warnings,
    ];
  });
}

export async function writeKarmaTres(json: KarmaImpact): Promise<TresWriteResult> {
  if (!shouldWriteTres()) return NOT_ATTEMPTED;
  const root = config.godotProjectRoot!;
  const found = await findKarmaTres(root, json.Id);
  if (!found) return { attempted: true, ok: false, error: `no .tres for karma id "${json.Id}"` };
  return runWrite(found.path, (doc) => {
    const result = applyKarma(doc, json as KarmaJson);
    return result.warnings;
  });
}

export async function writeQuestTres(json: Quest): Promise<TresWriteResult> {
  if (!shouldWriteTres()) return NOT_ATTEMPTED;
  const root = config.godotProjectRoot!;
  const found = await findQuestTres(root, json.Id);
  if (!found) return { attempted: true, ok: false, error: `no .tres for quest id "${json.Id}"` };

  // Pre-resolve UIDs the mapper may need.
  const itemSlugs = new Set<string>();
  for (const o of json.Objectives) if (o.TargetItem) itemSlugs.add(o.TargetItem);
  for (const r of json.Rewards) if (r.Item) itemSlugs.add(r.Item);
  const itemCache = new Map<string, { uid: string; resPath: string } | null>();
  for (const slug of itemSlugs) {
    itemCache.set(slug, await readItemUid(root, slug));
  }
  const objScriptUid =
    json.Objectives.length > 0
      ? await findScriptUidInProject(root, "res://shared/components/quest/QuestObjective.cs")
      : null;
  const rwdScriptUid =
    json.Rewards.length > 0
      ? await findScriptUidInProject(root, "res://shared/components/quest/QuestReward.cs")
      : null;
  const ctx: QuestApplyContext = {
    resolveItem: (s) => itemCache.get(s) ?? null,
    resolveObjectiveScriptUid: () => objScriptUid,
    resolveRewardScriptUid: () => rwdScriptUid,
  };

  return runWrite(found.path, (doc) => {
    const result = applyQuest(doc, json as QuestJson, ctx);
    return result.warnings;
  });
}

export async function writeBalloonTres(
  folder: string,
  json: Balloon,
): Promise<TresWriteResult> {
  if (!shouldWriteTres()) return NOT_ATTEMPTED;
  const root = config.godotProjectRoot!;
  const found = await findBalloonTres(root, folder, json.Id);
  if (!found) {
    return {
      attempted: true,
      ok: false,
      error: `no .tres at characters/npcs/${folder}/balloons/${json.Id}.tres`,
    };
  }
  return runWrite(found.path, (doc) => {
    const result = applyBalloonScalars(doc, json as BalloonJson);
    return result.warnings;
  });
}

export async function writeDialogTres(
  folder: string,
  json: DialogSequence,
): Promise<TresWriteResult> {
  if (!shouldWriteTres()) return NOT_ATTEMPTED;
  const root = config.godotProjectRoot!;
  const found = await findDialogTres(root, folder, json.Id);
  if (!found) {
    return {
      attempted: true,
      ok: false,
      error: `no .tres at */dialogs/${folder}/${json.Id}.tres`,
    };
  }

  // Pre-resolve portrait UIDs and DialogChoice.cs script UID.
  const portraitPaths = new Set<string>();
  for (const line of json.Lines) if (line.Portrait) portraitPaths.add(line.Portrait);
  const textureUidCache = new Map<string, string | null>();
  for (const p of portraitPaths) {
    textureUidCache.set(p, await readTextureUid(p));
  }
  const needsChoiceScript = json.Lines.some((l) => l.Choices.length > 0);
  const choiceScriptUid = needsChoiceScript
    ? await findScriptUidInProject(root, "res://shared/components/dialog/DialogChoice.cs")
    : null;
  const ctx: DialogApplyContext = {
    godotRoot: root,
    resolveTextureUid: (abs) => textureUidCache.get(abs) ?? null,
    resolveDialogChoiceScriptUid: () => choiceScriptUid,
  };

  return runWrite(found.path, (doc) => {
    const result = applyDialog(doc, json as DialogSequenceJson, ctx);
    return result.warnings;
  });
}

// ---- Atomic write with safety guard ---------------------------------------

async function runWrite(
  absPath: string,
  apply: (doc: ReturnType<typeof parseTres>) => string[],
): Promise<TresWriteResult> {
  // Defense in depth: refuse to write outside the configured Godot root.
  const root = config.godotProjectRoot!;
  const rel = absPath.startsWith(root + sep) ? absPath.substring(root.length + 1) : null;
  if (!rel) {
    return {
      attempted: true,
      ok: false,
      error: `refusing to write outside GODOT_PROJECT_ROOT: ${absPath}`,
    };
  }
  let original: string;
  try {
    original = await readFile(absPath, "utf8");
  } catch (err) {
    return { attempted: true, ok: false, error: `read failed: ${(err as Error).message}` };
  }
  let warnings: string[];
  let emitted: string;
  try {
    const doc = parseTres(original);
    warnings = apply(doc);
    // Final pass: drop any ext_resource that's no longer referenced. Catches
    // orphans introduced by the apply (e.g. swapping a LootEntry's
    // PickupScene leaves the previous PackedScene ref unused) AND any
    // pre-existing orphans on disk — incidental cleanup is intentional.
    const removedIds = removeOrphanExtResources(doc);
    if (removedIds.length > 0) {
      warnings.push(
        `removed ${removedIds.length} orphan ext_resource${
          removedIds.length === 1 ? "" : "s"
        }: ${removedIds.join(", ")}`,
      );
    }
    emitted = emitTres(doc);
  } catch (err) {
    return { attempted: true, ok: false, error: `mapper threw: ${(err as Error).message}` };
  }
  if (emitted === original) {
    return { attempted: true, ok: true, path: absPath, warnings };
  }
  // Atomic write: temp file in same dir, then rename.
  const tmp = `${absPath}.bleepforge.${process.pid}.${Date.now()}.tmp`;
  try {
    await writeFile(tmp, emitted, "utf8");
    // Record before the rename so the watcher event (which fires post-rename)
    // sees our flag.
    noteSelfWrite(absPath);
    await rename(tmp, absPath);
  } catch (err) {
    return { attempted: true, ok: false, error: `write failed: ${(err as Error).message}` };
  }
  return { attempted: true, ok: true, path: absPath, warnings };
}

// ---- Filesystem locators --------------------------------------------------
//
// All locators read from the runtime ProjectIndex (built at boot, kept
// live by the watcher). The index is content-classified, so the .tres
// can live anywhere in the Godot project — the writer doesn't care where.
// `godotRoot` is kept on the signature for callsite stability but unused.

async function findItemTres(
  _godotRoot: string,
  slug: string,
): Promise<{ path: string } | null> {
  const entry = projectIndex.get("item", slug);
  return entry ? { path: entry.absPath } : null;
}

async function findKarmaTres(
  _godotRoot: string,
  id: string,
): Promise<{ path: string } | null> {
  const entry = projectIndex.get("karma", id);
  return entry ? { path: entry.absPath } : null;
}

async function findNpcTres(
  _godotRoot: string,
  npcId: string,
): Promise<{ path: string } | null> {
  const entry = projectIndex.get("npc", npcId);
  return entry ? { path: entry.absPath } : null;
}

async function findFactionTres(
  _godotRoot: string,
  faction: string,
): Promise<{ path: string } | null> {
  const entry = projectIndex.get("faction", faction);
  return entry ? { path: entry.absPath } : null;
}

async function findQuestTres(
  _godotRoot: string,
  id: string,
): Promise<{ path: string } | null> {
  const entry = projectIndex.get("quest", id);
  return entry ? { path: entry.absPath } : null;
}

async function findDialogTres(
  _godotRoot: string,
  _folder: string,
  id: string,
): Promise<{ path: string } | null> {
  // DialogSequence Ids are globally unique by spec (DialogRegistry errors
  // on duplicates), so folder is not needed for the lookup — kept on the
  // signature for callsite stability.
  const entry = projectIndex.get("dialog", id);
  return entry ? { path: entry.absPath } : null;
}

async function findBalloonTres(
  _godotRoot: string,
  folder: string,
  id: string,
): Promise<{ path: string } | null> {
  // BalloonLine has no Id field in C#; the index key is the composite
  // "<model>/<basename>".
  const entry = projectIndex.get("balloon", `${folder}/${id}`);
  return entry ? { path: entry.absPath } : null;
}

// Re-exported for callers (e.g. dialogRouter, jsonCrud) that need to know
// where the project root currently points.
export const _internalForTests = { dirname, resolve };
